vim.g.mapleader = " "
vim.keymap.set("n", "<leader>tt", vim.cmd.Ex)
vim.keymap.set("n", "<leader>ns", ":vsplit<CR><C-w>w:Ex<CR>")
vim.keymap.set("n", "<leader>nn", vim.cmd.tabe)
vim.keymap.set("n", "<C-s>", ":w<CR>")
vim.keymap.set("n", "<leader>[s", ":normal! mz[s1z=`z<CR>")
vim.keymap.set("n", "<F2>", "<cmd>tabnew<CR>:e ~/PhD_work/Notes/keybinds.md<CR>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '>-2<CR>gv=gv")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("x", "<leader>p", "\"_dP")
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "<F3>" , function() vim.lsp.buf.format() end)
vim.keymap.set("n", "<leader>tms", "<cmd>silent !tmux neww tmux-sessionizer<CR>")
vim.keymap.set("n", "<leader>d", "\"_dd", {desc = 'Banish the line for eternity, no storing it in the buffer'})
