vim.g.mapleader = " "
vim.keymap.set("n", "<leader>tt", vim.cmd.Ex)
vim.keymap.set("n", "<leader>ns", ":vsplit<CR><C-w><C-w>:Ex<CR>")
vim.keymap.set("n", "<leader>nn", vim.cmd.tabe)
vim.keymap.set("n", "<C-s>", ":w<CR>")
vim.keymap.set("i", "(", "()<left>")
vim.keymap.set("i", "{", "{}<left>")
vim.keymap.set("i", "[", "[]<left>")
vim.keymap.set("i", "`", "``<left>")
vim.keymap.set("i", "'", "''<left>")
vim.keymap.set("i", '"', '""<left>')
vim.keymap.set("i", "<C-]>", "<C-[>A")
